Resources:
  ElastiCachePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - elasticache:AddTagsToResource
          - elasticache:AuthorizeCacheSecurityGroupIngress
          - elasticache:CreateCacheCluster
          - elasticache:CreateCacheSubnetGroup
          - elasticache:CreateReplicationGroup
          - elasticache:DeleteCacheCluster
          - elasticache:DeleteCacheSubnetGroup
          - elasticache:DeleteReplicationGroup
          - elasticache:DescribeCacheClusters
          - elasticache:DescribeCacheSecurityGroups
          - elasticache:DescribeCacheSubnetGroups
          - elasticache:DescribeReplicationGroup
          - elasticache:DescribeReplicationGroups
          - elasticache:DescribeEvents
          - elasticache:ListTagsForResource
          - elasticache:ModifyCacheCluster
          - elasticache:ModifyCacheSubnetGroup
          - elasticache:RemoveTagsFromResource
          - elasticache:RevokeCacheSecurityGroupIngress
          Resource: '*'
          Effect: Allow
        - Action:
          - iam:CreateServiceLinkedRole
          - iam:PutRolePolicy
          Resource: 'arn:aws:iam::*:role/aws-service-role/elasticache.amazonaws.com/AWSServiceRoleForElastiCache*'
          Condition:
            StringLike:
              iam:AWSServiceName: elasticache.amazonaws.com
          Effect: Allow
      Roles:
        - Ref: CloudFormationRole
