Parameters:
  NumCacheNodes:
    Type: String
    Description: Number of cache nodes
    Default: 2
  CacheNodeType:
    Type: String
    Description: The compute and memory capacity of the node(s) in the Redis Cluster
    Default: "cache.t2.micro"
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.m5.24xlarge
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.m3.medium
      - cache.m3.large
      - cache.m3.xlarge
      - cache.m3.2xlarge
      - cache.r5.24xlarge
      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
      - cache.r3.large
      - cache.r3.xlarge
      - cache.r3.2xlarge
      - cache.r3.4xlarge
      - cache.r3.8xlarge
  AutomaticFailoverEnabled:
    Type: String
    Description: Indicates whether Multi-AZ is enabled. When Multi-AZ is enabled, a read-only replica is automatically promoted to a read-write primary cluster if the existing primary cluster fails.  
    Default: "true"

Resources:
  ElasticacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: "Elasticache Subnet Group Name"
      SubnetIds:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              Ref: ServiceSubnetIds

  ElasticacheSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Elasticache Security Group"
      VpcId:
        Fn::ImportValue:
          Ref: VpcId
      SecurityGroupIngress:
        -
          IpProtocol: "tcp"
          FromPort: "6379"
          ToPort: "6379"
          SourceSecurityGroupId:
            Fn::ImportValue:
              Ref: ServiceSecurityGroup

  ElasticacheCluster:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties:
      Engine: "redis"
      CacheNodeType:
        Ref: CacheNodeType
      NumCacheClusters:
        Ref: NumCacheNodes
      CacheSubnetGroupName:
        Ref: ElasticacheSubnetGroup
      AutomaticFailoverEnabled:
        Ref: AutomaticFailoverEnabled
      ReplicationGroupDescription:
        Fn::Sub: ${Namespace}-${ServiceName}-${EnvironmentName}-cache
      SecurityGroupIds:
        - Fn::ImportValue:
            Ref: ServiceSecurityGroup

Outputs:
  ElasticacheClusterEndpointAddress:
    Description: "Elastic Cache Cluster Endpoint Address"
    Value: 
      Fn::Sub:
        ${ElasticacheCluster.PrimaryEndPoint.Address}
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ElasticacheClusterEndpointAddress
  ElasticacheClusterEndpointPort:
    Description: "Elastic Cache Cluster Endpoint Port"
    Value: 
      Fn::Sub:
        ${ElasticacheCluster.PrimaryEndPoint.Port}
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ElasticacheClusterEndpointPort
